<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>false</InvariantGlobalization>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<NoWarn>CS1591;CS1572;CS1573</NoWarn>

		<!-- 只保留当前平台运行时，减少 bin 目录体积 -->
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>

		<!-- 屏蔽语言包 -->
		<SatelliteResourceLanguages>none</SatelliteResourceLanguages>
		<GenerateSatelliteAssemblies>false</GenerateSatelliteAssemblies>
		<UseResourceManifest>false</UseResourceManifest>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="yswenli.png" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="yswenli.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LuBan.EMailKit\LuBan.EMailKit.csproj" />
		<ProjectReference Include="..\LuBan.Web.Core\LuBan.Web.Core.csproj" />
		<ProjectReference Include="..\LuBan.Wechat\LuBan.Wechat.csproj" />
		<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\face-recognition.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\files\" />
	</ItemGroup>

</Project>
