//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuBan.Orm {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrmResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrmResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuBan.Orm.OrmResource", typeof(OrmResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /****************************************************************************
        ///*Copyright @ yswenli All Rights Reserved.此代码由CodeGenerator.GetEntityCSCode工具生成。
        ///*CLR版本： net8.0
        ///*机器名称：WALLE
        ///*公司名称：Walle
        ///*命名空间：
        ///*文件名：  {{ClassName}}
        ///*版本号： V1.0.0.0
        ///*唯一标识：a5bb6173-b22d-4edd-852f-9b02bb075167
        ///*当前的用户域：WALLE
        ///*创建人： yswenli
        ///*电子邮箱：yswenli@outlook.com
        ///*创建时间：{{DateTime}}
        ///*描述：{{Description}}
        ///*
        ///*=================================================
        ///*修改标记
        ///*修改时间：{{DateTime}}
        ///*修改人： yswenli
        ///*版本号： V1.0.0.0
        ///*描述：{{Des [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EntityTemplate {
            get {
                return ResourceManager.GetString("EntityTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /****************************************************************************
        ///*Copyright @ yswenli All Rights Reserved. 此代码由CodeGenerator.GetSeedDataCSCode工具生成。
        ///*CLR版本： net8.0
        ///*机器名称：WALLE
        ///*公司名称：Walle
        ///*命名空间：LuBan.Orm.Seeds
        ///*文件名： {{ClassName}}
        ///*版本号： V1.0.0.0
        ///*唯一标识：a5bb6173-b22d-4edd-852f-9b02bb075167
        ///*当前的用户域：WALLE
        ///*创建人： yswenli
        ///*电子邮箱：yswenli@outlook.com
        ///*创建时间：{{DateTime}}
        ///*描述：{{Description}}
        ///*
        ///*=================================================
        ///*修改标记
        ///*修改时间：{{DateTime}}
        ///*修改人： yswenli
        ///*版本号：  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SeedDataTemplate {
            get {
                return ResourceManager.GetString("SeedDataTemplate", resourceCulture);
            }
        }
    }
}
